use anyhow::{anyhow, Context, Result};
use k8dnz_apextrace::{analyze_key_against_bytes, brute_force_best, generate_bytes, generate_quats, ApexKey, SearchCfg};

use crate::cmd::apextrace::{FitArgs, GenArgs, InspectArgs, PackArgs, RenderArgs, RenderFormat, RenderMode};
use super::common::{
    match_pct, render_base_csv, render_base_txt, render_lattice_csv, render_lattice_txt,
    render_paths_csv, render_paths_txt, render_quats_ascii, write_or_print,
};

pub fn run_pack(args: PackArgs) -> Result<()> {
    let key = ApexKey::new_dibit_v1(args.byte_len, args.root_quadrant, args.root_seed, args.recipe_seed)?;
    let enc = key.encode()?;
    std::fs::write(&args.out, enc).with_context(|| format!("write {}", args.out))?;
    eprintln!(
        "apextrace pack ok: out={} bytes={} quat_len={} depth={} root_quadrant={} root_seed=0x{:016X} recipe_seed=0x{:016X}",
        args.out, key.byte_len, key.quat_len, key.depth, key.root_quadrant, key.root_seed, key.recipe_seed
    );
    Ok(())
}

pub fn run_inspect(args: InspectArgs) -> Result<()> {
    let bytes = std::fs::read(&args.atk).with_context(|| format!("read {}", args.atk))?;
    let key = ApexKey::decode(&bytes)?;
    println!("file={}", args.atk);
    println!("version={}", key.version);
    println!("mode={}", key.mode);
    println!("law_id={}", key.law_id);
    println!("byte_len={}", key.byte_len);
    println!("quat_len={}", key.quat_len);
    println!("depth={}", key.depth);
    println!("root_quadrant={}", key.root_quadrant);
    println!("root_seed=0x{:016X}", key.root_seed);
    println!("recipe_seed=0x{:016X}", key.recipe_seed);
    Ok(())
}

pub fn run_gen(args: GenArgs) -> Result<()> {
    let bytes = std::fs::read(&args.atk).with_context(|| format!("read {}", args.atk))?;
    let key = ApexKey::decode(&bytes)?;
    if args.quats {
        let quats = generate_quats(&key)?;
        let text = render_quats_ascii(&quats);
        match args.out {
            Some(path) => {
                std::fs::write(&path, text.as_bytes()).with_context(|| format!("write {}", path))?;
                eprintln!("apextrace gen ok: out={} mode=quats symbols={}", path, quats.len());
            }
            None => println!("{text}"),
        }
    } else {
        let out_bytes = generate_bytes(&key)?;
        match args.out {
            Some(path) => {
                std::fs::write(&path, &out_bytes).with_context(|| format!("write {}", path))?;
                eprintln!("apextrace gen ok: out={} mode=bytes bytes={}", path, out_bytes.len());
            }
            None => std::io::Write::write_all(&mut std::io::stdout(), &out_bytes)?,
        }
    }
    Ok(())
}

pub fn run_fit(args: FitArgs) -> Result<()> {
    let target = std::fs::read(&args.r#in).with_context(|| format!("read {}", args.r#in))?;
    let cfg = SearchCfg {
        seed_from: args.seed_from,
        seed_count: args.seed_count,
        seed_step: args.seed_step,
        recipe_seed: args.recipe_seed,
    };
    let best = brute_force_best(&target, cfg)?;
    let diag = analyze_key_against_bytes(&best.key, &target)?;
    println!("input={}", args.r#in);
    println!("byte_len={}", best.key.byte_len);
    println!("quat_len={}", best.key.quat_len);
    println!("depth={}", best.key.depth);
    println!("best_root_quadrant={}", best.key.root_quadrant);
    println!("best_root_seed=0x{:016X}", best.key.root_seed);
    println!("recipe_seed=0x{:016X}", best.key.recipe_seed);
    println!("matches={}", diag.score.matches);
    println!("prefix={}", diag.score.prefix);
    println!("total={}", diag.score.total);
    println!("match_pct={:.6}", match_pct(diag.score.matches, diag.score.total));
    println!("hamming={}", diag.score.hamming());
    println!("byte_matches={}", diag.byte_matches);
    println!("longest_run={}", diag.longest_run);
    println!("longest_run_start={}", diag.longest_run_start);
    println!("target_hist_1={}", diag.target_hist[0]);
    println!("target_hist_2={}", diag.target_hist[1]);
    println!("target_hist_3={}", diag.target_hist[2]);
    println!("target_hist_4={}", diag.target_hist[3]);
    println!("pred_hist_1={}", diag.pred_hist[0]);
    println!("pred_hist_2={}", diag.pred_hist[1]);
    println!("pred_hist_3={}", diag.pred_hist[2]);
    println!("pred_hist_4={}", diag.pred_hist[3]);
    if let Some(path) = args.out_key {
        let enc = best.key.encode()?;
        std::fs::write(&path, enc).with_context(|| format!("write {}", path))?;
        eprintln!("saved apex key: {}", path);
    }
    if let Some(path) = args.gen_out {
        let bytes = generate_bytes(&best.key)?;
        std::fs::write(&path, bytes).with_context(|| format!("write {}", path))?;
        eprintln!("saved generated bytes: {}", path);
    }
    Ok(())
}

pub fn run_render(args: RenderArgs) -> Result<()> {
    let key = resolve_key_for_render(&args)?;
    let body = match (args.mode, args.format) {
        (RenderMode::Lattice, RenderFormat::Csv) => render_lattice_csv(&key, args.max_quats, args.active_only)?,
        (RenderMode::Lattice, RenderFormat::Txt) => render_lattice_txt(&key, args.max_quats, args.active_only)?,
        (RenderMode::Paths, RenderFormat::Csv) => render_paths_csv(&key, args.max_quats)?,
        (RenderMode::Paths, RenderFormat::Txt) => render_paths_txt(&key, args.max_quats)?,
        (RenderMode::Base, RenderFormat::Csv) => render_base_csv(&key, args.max_quats)?,
        (RenderMode::Base, RenderFormat::Txt) => render_base_txt(&key, args.max_quats)?,
    };
    write_or_print(args.out.as_deref(), &body)?;
    if let Some(path) = args.out.as_deref() {
        eprintln!("apextrace render ok: out={} mode={:?} format={:?}", path, args.mode, args.format);
    }
    Ok(())
}

fn resolve_key_for_render(args: &RenderArgs) -> Result<ApexKey> {
    match (&args.atk, &args.r#in) {
        (Some(_), Some(_)) => Err(anyhow!("render accepts either --atk or --in, not both")),
        (None, None) => Err(anyhow!("render requires either --atk or --in")),
        (Some(path), None) => {
            let bytes = std::fs::read(path).with_context(|| format!("read {}", path))?;
            ApexKey::decode(&bytes).map_err(Into::into)
        }
        (None, Some(path)) => {
            let target = std::fs::read(path).with_context(|| format!("read {}", path))?;
            resolve_key_for_target(
                None,
                &target,
                args.seed_from,
                args.seed_count,
                args.seed_step,
                args.recipe_seed,
                args.out_key.as_deref(),
                "render",
            )
        }
    }
}

pub fn resolve_key_for_target(
    atk: Option<&str>,
    target: &[u8],
    seed_from: u64,
    seed_count: u64,
    seed_step: u64,
    recipe_seed: u64,
    out_key: Option<&str>,
    verb: &str,
) -> Result<ApexKey> {
    match atk {
        Some(path) => {
            let bytes = std::fs::read(path).with_context(|| format!("read {}", path))?;
            ApexKey::decode(&bytes).map_err(Into::into)
        }
        None => {
            let cfg = SearchCfg { seed_from, seed_count, seed_step, recipe_seed };
            let best = brute_force_best(target, cfg)?;
            eprintln!(
                "apextrace {} fit: byte_len={} quat_len={} depth={} root_quadrant={} root_seed=0x{:016X} recipe_seed=0x{:016X} matches={} total={} match_pct={:.6}",
                verb,
                best.key.byte_len,
                best.key.quat_len,
                best.key.depth,
                best.key.root_quadrant,
                best.key.root_seed,
                best.key.recipe_seed,
                best.score.matches,
                best.score.total,
                match_pct(best.score.matches, best.score.total)
            );
            if let Some(out_key) = out_key {
                let enc = best.key.encode()?;
                std::fs::write(out_key, enc).with_context(|| format!("write {}", out_key))?;
                eprintln!("saved apex key: {}", out_key);
            }
            Ok(best.key)
        }
    }
}
