use super::types::{LawProgramArtifact, ProgramFile, ProgramOverride, ProgramSummary, ProgramWindow, ReplayConfig};

#[test]
fn artifact_roundtrip() {
    let artifact = LawProgramArtifact {
        config: ReplayConfig {
            recipe: "configs/tuned_validated.k8r".to_string(),
            inputs: vec!["text/Genesis1.txt".to_string()],
            max_ticks: 20,
            window_bytes: 256,
            step_bytes: 256,
            max_windows: 12,
            seed_from: 0,
            seed_count: 64,
            seed_step: 1,
            recipe_seed: 1,
            chunk_sweep: "32,64".to_string(),
            chunk_search_objective: "raw".to_string(),
            chunk_raw_slack: 1,
            map_max_depth: 0,
            map_depth_shift: 1,
            boundary_band_sweep: "8,12".to_string(),
            boundary_delta: 1,
            field_margin_sweep: "4,8".to_string(),
            newline_margin_add: 96,
            space_to_newline_margin_add: 64,
            newline_share_ppm_min: 550_000,
            newline_override_budget: 0,
            newline_demote_margin_sweep: "0,4".to_string(),
            newline_demote_keep_ppm_min: 150_000,
            newline_demote_keep_min: 1,
            newline_only_from_spacelike: true,
            merge_gap_bytes: 0,
            allow_overlap_scout: false,
            freeze_boundary_band: Some(12),
            freeze_field_margin: Some(4),
            freeze_newline_demote_margin: Some(4),
            local_chunk_sweep: "32,64,96,128".to_string(),
            local_chunk_search_objective: None,
            local_chunk_raw_slack: None,
            default_local_chunk_bytes_arg: Some(96),
            tune_default_body: true,
            default_body_chunk_sweep: Some("64,96,128".to_string()),
            body_select_objective: "selected-total".to_string(),
            emit_body_scoreboard: true,
            min_override_gain_exact: 1,
            exact_subset_limit: 20,
            global_law_id_arg: Some("G1".to_string()),
        },
        summary: ProgramSummary {
            recipe: "configs/tuned_validated.k8r".to_string(),
            file_count: 1,
            honest_file_count: 1,
            union_law_count: 2,
            target_global_law_id: "G1".to_string(),
            target_global_law_path_hits: 5,
            target_global_law_file_count: 1,
            target_global_law_total_window_count: 3,
            target_global_law_total_segment_count: 2,
            target_global_law_total_covered_bytes: 768,
            target_global_law_dominant_knob_signature:
                "chunk_bytes=64|chunk_search_objective=raw|chunk_raw_slack=1".to_string(),
            eval_boundary_band: 12,
            eval_field_margin: 4,
            eval_newline_demote_margin: 4,
            eval_chunk_search_objective: "raw".to_string(),
            eval_chunk_raw_slack: 1,
            eval_chunk_candidates: "32,64,96,128".to_string(),
            eval_chunk_candidate_count: 4,
            default_local_chunk_bytes: 96,
            default_local_chunk_window_wins: 2,
            searched_total_piecewise_payload_exact: 2200,
            projected_default_total_piecewise_payload_exact: 2128,
            delta_default_total_piecewise_payload_exact: -72,
            projected_unpriced_best_mix_total_piecewise_payload_exact: 2119,
            delta_unpriced_best_mix_total_piecewise_payload_exact: -81,
            selected_total_piecewise_payload_exact: 2126,
            delta_selected_total_piecewise_payload_exact: -74,
            target_window_count: 3,
            searched_target_window_payload_exact: 600,
            default_target_window_payload_exact: 520,
            best_mix_target_window_payload_exact: 510,
            selected_target_window_payload_exact: 512,
            delta_selected_target_window_payload_exact: -88,
            override_path_mode: "delta".to_string(),
            override_path_bytes_exact: 7,
            selected_override_window_count: 1,
            improved_target_window_count: 2,
            equal_target_window_count: 1,
            worsened_target_window_count: 0,
        },
        files: vec![ProgramFile {
            input: "text/Genesis1.txt".to_string(),
            searched_total_piecewise_payload_exact: 2200,
            projected_default_total_piecewise_payload_exact: 2128,
            projected_unpriced_best_mix_total_piecewise_payload_exact: 2119,
            selected_total_piecewise_payload_exact: 2126,
            target_window_count: 3,
            override_path_mode: "delta".to_string(),
            override_path_bytes_exact: 7,
            selected_override_window_count: 1,
        }],
        windows: vec![ProgramWindow {
            input_index: 0,
            input: "text/Genesis1.txt".to_string(),
            window_idx: 0,
            target_ordinal: 0,
            start: 0,
            end: 256,
            span_bytes: 256,
            searched_payload_exact: 200,
            default_payload_exact: 180,
            best_payload_exact: 170,
            selected_payload_exact: 170,
            searched_chunk_bytes: 64,
            best_chunk_bytes: 32,
            selected_chunk_bytes: 32,
            selected_gain_exact: 30,
        }],
        overrides: vec![ProgramOverride {
            input_index: 0,
            input: "text/Genesis1.txt".to_string(),
            window_idx: 0,
            target_ordinal: 0,
            best_chunk_bytes: 32,
            default_payload_exact: 180,
            best_payload_exact: 170,
            gain_exact: 10,
        }],
    };

    let bytes = artifact.encode().expect("encode artifact");
    let decoded = LawProgramArtifact::decode(&bytes).expect("decode artifact");

    assert_eq!(artifact.config, decoded.config);
    assert_eq!(artifact.summary, decoded.summary);
    assert_eq!(artifact.files, decoded.files);
    assert_eq!(artifact.windows, decoded.windows);
    assert_eq!(artifact.overrides, decoded.overrides);
}